config/routes.rb
Rails.application.routes.draw do
  root 'promocode#activate'
  post '/activation', to: 'promocode#activation'
  get '/promocodes', to: 'promocode#index'
  get '/promocodes/generate', to: 'promocode#generate'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/promocode.rb
class Promocode < ApplicationRecord
  has_one :user_transaction

  validates :code, uniqueness: true

  scope :active, -> { where(active: true) }

  def self.generate(amount)
    code = SecureRandom.urlsafe_base64(8, false)
    create(code: code, amount: amount, active: true)
  end

  def activate(user)
    self.active = false
    self.user_transaction = UserTransaction.new(
      amount: amount,
      user_balance: user.user_balance
    )
    save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :user_balance

  after_create :create_balance

  def create_balance
    UserBalance.generate(id)
  end
end

app/models/user_balance.rb
class UserBalance < ApplicationRecord
  belongs_to :user
  has_many :user_transactions

  def self.generate(user_id)
    create(user_id: user_id, amount: 0)
  end
end

app/models/user_transaction.rb
class UserTransaction < ApplicationRecord
  belongs_to :promocode
  belongs_to :user_balance

  after_create :change_balance

  private

  def change_balance
    balance = user_balance.amount + amount
    user_balance.update_attributes(amount: balance)
    self.finished = true
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/promocode_controller.rb
class PromocodeController < ApplicationController
  before_action :authenticate_user!

  def activate
    @promocode = Promocode.new
  end

  def activation
    # promocode = Promocode.where(
    #   code: promocode_params[:code],
    #   active: true
    # ).lock(true).
    promocode = Promocode
      .active
      .find_by_code(promocode_params[:code])
      .lock(true)
    if promocode.present?
      promocode.activate(current_user)
    else
      flash[:error] = 'Bad promocode'
    end
    redirect_to '/'
  end

  def index
    @promocodes = Promocode.all
  end

  def generate
    Promocode.generate(200)
    redirect_to '/promocodes'
  end

  private

  def promocode_params
    params.require(:promocode).permit(:code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/promocode_helper.rb
module PromocodeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/promocode/activate.html.slim
h1 Promocode#activate
p Find me in app/views/promocode/activate.html.erb

= form_for @promocode, url: { action: :activation } do |f|
  = f.label :code
  = f.text_field :code

  = f.submit "Activate!"

= link_to "list of promocodes", '/promocodes'

app/views/promocode/index.slim
- @promocodes.each do |promocode|
  p #{promocode.code} #{promocode.active}

= link_to 'Generate', promocodes_generate_path